[theme]
theme = "space-villain"

[theme.overrides]
idle_bg = "#081014"
idle_fg = "#c0c0c0"
warning_bg = "#081014"
warning_fg = "#c0c0c0"
info_bg = "#081014"
info_fg = "#c0c0c0"
good_bg = "#081014"
good_fg = "#c0c0c0"
critical_bg = "#081014"
critical_fg = "#c0c0c0"
separator_bg = "#081014"
separator_fg = "#646464"
separator = "││"

[icons]
icons = "none"

[icons.overrides]
thermometer = "CPU TEMP"
time = "TIME"
memory_mem = "MEM"
gpu = "GPU"
cpu = "CPU"

[[block]]
block = "disk_space"
path =  "/"
info_type = "used"
format = " $icon $used/$total "

[[block]]
block = "sound"
max_vol = 100
step_width = 5

[[block]]
block = "backlight"

[[block]]
block = "battery"
driver = "upower"
format = " $icon $percentage "
full_format = " $icon $percentage "

[[block]]
block = "nvidia_gpu"
format = "​ GTX 1650 $utilization $memory.eng(w:3) $temperature "
interval = 5

[[block]]
block = "memory"
format = " $icon $mem_used.eng(w:4)/$mem_total.eng(w:3) $mem_used_percents "

[[block]]
block = "cpu"
format = " $icon $barchart $utilization $frequency.eng(w:3) "
interval = 1

[[block]]
block = "temperature"
chip = "k10temp-pci-00c3"
format = " $icon $average "

[[block]]
block = "time"
interval = 1
format = " $icon $timestamp.datetime(f:'%a %d.%m.%Y %H:%M:%S') "
